= Ordlista

[glossary]
attribut:: Data som lagras i en instans, skapas med _instansvariabler_ (variabler som börjar med `@`, t.ex `@phone_number`).
camelCase:: Ett sätt att namnge kod (metoder/klasser/variabler etc), där första ordet i namnet börjar med en gemen, och om namnet innehåller flera ord börjar följande ord med en versal `points`, `healthPoints`, `currentUser`. Används *inte* i Ruby (men i t.ex javascript).
metod:: En funktion som är definerad inne i en klass
klassmetod:: En metod som är definerad på klassen. Anropas genom `KlassensNamn.metodens_namn`. Skapas genom `def self.metodens_namn`
instansmetod:: En metod som anropas på instanser av klassen. Anropas genom `instansens_variabel.metodens_namn`. Skapas genom `def metodens_namn`
instansvariabel:: Se *attribut*
nyckelord:: Ett ord som är reserverat och betyder något speciellt i programmeringsspråket, och därför inte kan användas till något annat. T.ex `class`, `if`, `end`, `def`.
PascalCase:: Ett sätt att namnge kod (metoder/klasser/variabler etc), där varje ord i namnet börjar med en versal. T.ex `User`, `BankAccount` eller `HTTPRequest`. Används i Ruby för klassnamn.
snake_case:: Ett sätt att namnge kod (metoder/klasser/variabler etc), där varje ord i namnet börjar med en gemen, och om namnet innehåller flera ord länkas de ihop med understreck (`_`). T.ex `amount`, `current_user`, `total_time_in_seconds`. Används i Ruby för variabler och metoder.
kebab-case:: Ett sätt att namnge kod (metoder/klasser/variabler etc), där varje ord i namnet börjar med en gemen, och om namnet innehåller flera ord länkas de ihop med bindestreck (`-`). T.ex `velocity`, `current_user`, `total_time_in_seconds`. Används *inte* i Ruby (men i t.ex css). 
konstruktor:: En speciell metod som används när man skapar instanser/objekt av en klass. Anropas genom `KlassensNamn.new`
state:: Alla variabler och värdet på dessa vid ett givet tillfälle.